### ISSUE TITLE
[Fall 2021] Step 3: Add support for --output=sarif to pyre

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#50]
https://github.com/facebook/pyre-check/pull/427 added support for surfacing type errors inline on github through a script that takes the output of pyre --output=json and converts it into SARIF (https://github.com/microsoft/sarif-tutorials), the file format GitHub understands. Ideally there should be an easier way for projects to set up the integration by just running pyre --output=sarif. This task is about adding that support to pyre.

References:
GitHub CI setup and script generating SARIF format: https://github.com/facebook/pyre-check/pull/427  
Pyre printing logic: 
https://github.com/MLH-Fellowship/pyre-check/blob/master/client/error.py#L244

**Comment by abishekvashok** [comment]
I got this :)

**Comment by 0xedward** [comment]
Still working out Github Marketplace set up internally for this. We should be able to land @abishekvashok's PR after that

**Comment by abishekvashok** [comment]
@0xedward I am sorry, but can you provide me a update as to why we need a repo for this?
Are we creating actions for pyre as well? (In addition to pysa?) 

If not, I guess the pysa action won't need these changes as we'll use sapp there. 

I guess this was intended for pyre so that we could have sarif output natively rather than use a script for the GitHub actions in the pyre check repository.

**Comment by 0xedward** [comment]
@abishekvashok Oh, sorry, just saw this now!

> I am asking cause I believe we need a repo for the pysa action but are we creating an action for pyre as well?

Yep, that's the plan! :)

> I guess this issue was intended for pyre so that we could have sarif output natively rather than use a script for the GitHub actions in the pyre check repository.

Ah, that's right! I commented about the Github action for Pyre here, since that was the original goal to add `--output=sarif` to Pyre, but we can create a separate issue for the Pyre github action.

I'll check to see what is going on with the PR and if there's anything blocking it

**Comment by abishekvashok** [comment]
Hey @0xedward it's okay - I figured it out from yesterday's 1:1, it's an old comment.
